id: P003214
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:47:57.285991
source_metadata:
  id: bdr:W1KG25897
  title: དབྱང་ཚང་གི་དམག་དཔོན།
  author: ''
  volumes:
    4c007e5c671c42af89f9a72d9ad36d2f:
      image_group_id: I1KG25899
      title: ''
      volume_number: 1
      total_pages: 235
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
